apiVersion: v1
kind: PersistentVolumemetadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi  # Укажите необходимый объем хранилища
  accessModes:
    - ReadWriteMany  # Режимы доступа: ReadWriteOnce, ReadOnlyMany или ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Политика возврата: Retain, Delete или Recycle
  storageClassName: nfs-storage  # Имя StorageClass, должно совпадать с PVC
  nfs:
    path: /srv/nfs/k8s  # Путь на сервере NFS
    server: 192.168.33.101  # IP-адрес или DNS-имя сервера NFS
